### ISSUE TITLE
New Business Rule Required

### ISSUE THREAD

**Issue by lemendoza** [PabloDelgadoC/tallerSoftwareII#1]
NOTE: The new feature template should have been enabled.

*Is your feature request related to a problem? Please describe.*
This feature is not related to a problem. It is related to a new policy of the organization. 
Based on the impact of the pandemic in the 2020 results, the board of the company has approved a new business rule (policy) beginning january 2021, that needs to be included in our product. 

*Describe the solution you'd like*
The new business rule establishes: If the customer is male, over 25 and younger than 45 then it is needed to subtract $100 from the base premium.
Therefore, we ask you to modify the premium calculation adding this new rule. 

*Describe alternatives you've considered*
There is no alternative to be considered.

*Additional context*
I will provide you with more information if needed.

Best regards,
LEMM

**Comment by PabloDelgadoC** [comment]
It is not clear this announce, first, what I have to describe? second, what solution I have to apply? the business rule establishes is the solution or I have to put another one? and What do I have to describe alternatives about?

**Comment by lemendoza** [comment]
Since you didn't create a template (step 3 of workshop) for new features, I introduced the default one in GitHub. Those questions or sections (in Italic text) are for the customer to fill in. I submitted the completed template...
Proceed with the rest of the workshop!

**Comment by PabloDelgadoC** [comment]
I did all the 5 steps yesterday, now I have put the new rule policy in the code. So, can I continue with the workshop without problem?

**Comment by lemendoza** [comment]
Yes...

**Comment by PabloDelgadoC** [comment]
I have proceeded to categorize the issue

**Comment by PabloDelgadoC** [comment]
We will proceed to process the request, @PabloDelgadoC  will be the assigned analyst and  will develop the solution, and @eullaguari will perform the tests.

**Comment by PabloDelgadoC** [comment]
[Impact analysis - PEDIDOS.docx](https://github.com/PabloDelgadoC/tallerSoftwareII/files/5845367/Impact.analysis.-.PEDIDOS.docx)
The impact analysis has been performed. Do you @lemendoza  agree?

**Comment by lemendoza** [comment]
Ok. Proceed.

**Comment by lemendoza** [comment]
Sorry. Yes, I agree. Please, proceed.

**Comment by PabloDelgadoC** [comment]
https://github.com/PabloDelgadoC/tallerSoftwareII/blob/0384feba96002c841a0e1d8603eb7e5d52f3bd71/ec.edu.espol.workshops.second/src/main/java/ec/edu/espol/workshops/second/Main.java#L60-L64

**Comment by PabloDelgadoC** [comment]
@lemendoza here's the structure testing plan.
[S Testing Plan - PEDIDOS.pdf](https://github.com/PabloDelgadoC/tallerSoftwareII/files/5852791/S.Testing.Plan.-.PEDIDOS.pdf)

**Comment by PabloDelgadoC** [comment]
@lemendoza the Structural Testing Plan was executed and pass regarding the addition of the new requirement. We are going to proceed with the acceptance testing.

**Comment by PabloDelgadoC** [comment]
Do you @lemendoza agree with the attached Acceptance Testing Plan?
[A Testing Plan - PEDIDOS.pdf](https://github.com/PabloDelgadoC/tallerSoftwareII/files/5852827/A.Testing.Plan.-.PEDIDOS.pdf)

**Comment by lemendoza** [comment]
No, I do not agree. The Acceptance Testing Plan does not include a case to test the new requirement.

**Comment by PabloDelgadoC** [comment]
My bad, I attach the new Acceptance Testing Plan with the new requirement's test. Do you @lemendoza agree?
[A Testing Plan - PEDIDOS.pdf](https://github.com/PabloDelgadoC/tallerSoftwareII/files/5853149/A.Testing.Plan.-.PEDIDOS.pdf)

**Comment by lemendoza** [comment]
No, I do not agree. The 'new' Acceptance Testing Plan also does not include any case to test the new requirement...

**Comment by PabloDelgadoC** [comment]
Oh, sorry, now I got you. This is the real acceptance testing plan. Do you @lemendoza agree?
[A Testing Plan - PEDIDOS.pdf](https://github.com/PabloDelgadoC/tallerSoftwareII/files/5853226/A.Testing.Plan.-.PEDIDOS.pdf)

**Comment by lemendoza** [comment]
Yes, now I agree.

**Comment by PabloDelgadoC** [comment]
Ok, now the solution has been completed and @eullaguari will release the new software version for you @lemendoza

**Comment by eullaguari** [comment]
The new version of the code has been released @lemendoza  in order to use the new version of the code you should open you CLI (Command Line Interface) and move to the branch Issues_Management by using the command "git checkout Issues_Management". The code is located there, after that open Eclipse IDE and you can proceed to use the new code in the Main.java class. Finally, you can proceed to test the new code.

**Comment by PabloDelgadoC** [comment]
@lemendoza  were you able to use the new release of the system? If, are you satisfied with the solution provided?

**Comment by lemendoza** [comment]
Yes, I satisfied.
